apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergy-bot
spec:
  selector:
    matchLabels:
      app: synergy-bot
  template:
    metadata:
      labels:
        app: synergy-bot
    spec:
      containers:
      - name: synergy-bot
        image: reg.zackmyers.io/zack/synergy:v0.1.0
        env:
          - name: DISCORD_TOKEN
            value: Nzk3NjYyMTUzOTk3MDI1MzAw.X_puxQ.ReZB8UkgXXNuiTqnddnLYrtEKXo
          - name: DB_USER
            value: bot-admin
          - name: DB_PASS
            value: xPkVCla0Dg
          - name: DB_PORT
            value: '3306'
          - name: DB_HOST
            value: bot-db-mariadb.bots.svc.cluster.local
          - name: DB_NAME
            value: bot-db
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
